enableFeaturePreview("VERSION_CATALOGS")
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

include(":core-ui")
include(":core-network")
include(":core-testing")
include(":core-utils")
include(":core-extension")
include(":core-resource")
include(":core-data")
include(":p2p-server")
include(":p2p-client")
include(":p2p-streaming-kit")
include(":camera-kit")
include(":wifi-direct-kit")
include(":p2p-shared-resources")
